### ISSUE TITLE
Typo in K_{\nu} def?

### ISSUE THREAD

**Issue by LeanneDurkan** [BlackHolePerturbationToolkit/MST#1]
Typo in K_{\nu} def?
Should factor in  K_{\nu 1} be changed from \[Epsilon]^(**-1**-\[Nu]) to  \[Epsilon]^(**s**-\[Nu]) ?
Similarly for K_{\nu 2}

See CST165 and CO 3.32

**Comment by barrywardell** [comment]
Did you close this because you decided it wasn't a typo after all, or do we still need to look at it?
